apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
commonLabels:
  app.kubernetes.io/name: prometheus
resources:
- namespace.yaml
- role.yaml
- service-account.yaml
- clusterrole-binding.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
images:
- name: prom/prometheus
  newTag: latest
configMapGenerator:
- name: prometheus-configuration
  files:
  - prometheus.yaml